services:
  - type: web
    name: hostcloud-app
    env: node
    rootDir: cloud-file-transfer
    buildCommand: cd backend && rm -rf node_modules && npm ci && cd ../frontend && rm -rf node_modules && npm ci && npm run build
    startCommand: node backend/server.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        sync: false
